remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [el_googs' portfolio]
tagline: [4 years of full stack scripting]
description: [For you to see my past works & decide whether to comission me or not]
